# Generated by Django 4.1.6 on 2023-02-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
