# Generated by Django 4.1.6 on 2023-02-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task_app", "0003_auto_20230212_1719"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="is_done",
            field=models.BooleanField(),
        ),
    ]
